name: Maven Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                      <server>
                          <id>github</id>
                          <username>${{ secrets.GITHUB_ACTOR }}</username>
                          <password>${{ secrets.GITHUB_TOKEN }}</password>
                      </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Build and deploy
        run: mvn deploy
